### ISSUE TITLE
Post GitHub comment with Jira link

### ISSUE THREAD

**Issue by bgilbert** [release-engineering/Sync2Jira#126]
It seems that after adding the `jira` label to a GitHub issue, one has to go spelunking through Jira to locate the newly created card so it can be added to a sprint, etc.  Consider optionally posting a GitHub issue comment containing a link to the Jira card.

**Comment by nickboldt** [comment]
any further thoughts on implementing this? without it, the logical workflow becomes:

* find the new JIRA
* comment manually on the GH issue, and close it 
* do all subsequent work in JIRA

which means this tool is less about sync and more about "create a new JIRA and then stop using GH". 

If the goal is to be able to use GH issues for updates to an issue, AND have the same comments flow to JIRA, then having a link in the GH issue to that JIRA is :100: required for good UX. 

Spelunking is for caves, not for issue triage/maintenance & project health. :D

**Comment by Zyzyx** [comment]
I'm going to say this feature is available now, the key is using the `upstream_id` value in the `issue_updates` array. When it is specified like so:

```
        'map': {
            'pagure': {},
            'github': {
                'Zyzyx/issuetest': {
                    'project': 'TEST',
                    'sync': ['issue'],
                    'type': 'Task',
                    'issue_updates': [**'upstream_id'**, 'description']
                },
            },
        },
```

You'll see an "Issue Link" on the corresponding Jira:
![image](https://github.com/release-engineering/Sync2Jira/assets/950108/0ceb1d04-3f15-44ba-b7e7-f260b1d0c3f4)

... and a comment:

![image](https://github.com/release-engineering/Sync2Jira/assets/950108/042611bb-6342-44e0-b8ba-2ee202f7b87c)

I think this issue can be closed.

**Comment by ralphbean** [comment]
I agree!

**Comment by travier** [comment]
Hum, unless I'm missing something, this is not what this issue is about. You detail what is done in Jira, but this issue is about posting a comment on original GitHub issue once the clone is done in Jira.
