### ISSUE TITLE
Sync issue resolution

### ISSUE THREAD

**Issue by yrodiere** [release-engineering/Sync2Jira#209]
When an issue get closed as "not planned" in GitHub, I would like the resolution to be set consistently with the GitHub "resolution" (completed/not planned).

Maybe this could be implemented as a custom `on_close` option, e.g.:

```
'on_close': {
  'resolution': {
    'completed' : 'Done',
    'not_planned' : 'Won\' do'
  }
}
```

(I may work on this... someday :) )

**Comment by mattreid** [comment]
Hi @yrodiere, thanks for the suggestion. I think this is already covered in #170, would you agree?

**Comment by yrodiere** [comment]
Hey,

> I think this is already covered in https://github.com/release-engineering/Sync2Jira/issues/170, would you agree?

It is, sorry for the noise. Closing.
